DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
IDMATRICULA VARCHAR(50) NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 'MR1234', 'CARLOS', 'PEREZ');
INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 'JDS146', 'MARTIN', 'DE FRANCISCO');